"""
MedXplain-Simple — Clinical PDF report engine with findings and visual evidence.

Generates professional PDF reports containing:
- Patient/study metadata
- VQA analysis results
- Clinical reasoning and differential diagnosis
- Grad-CAM heatmap overlay
- Longitudinal comparison (if available)
- Recommendations
"""

from __future__ import annotations

import io
import base64
import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


@dataclass
class ReportData:
    """Data to include in a clinical PDF report."""

    patient_id: str = "ANONYMOUS"
    study_date: str = ""
    modality: str = ""
    body_part: str = ""
    clinical_question: str = ""
    vqa_answer: str = ""
    clinical_reasoning: str = ""
    differential_diagnosis: list[str] = None
    recommendations: list[str] = None
    confidence: float = 0.0
    heatmap_base64: Optional[str] = None
    comparison_base64: Optional[str] = None
    ssim_score: Optional[float] = None
    comparison_summary: Optional[str] = None
    model_used: str = ""
    processing_time_ms: float = 0.0

    def __post_init__(self):
        if self.differential_diagnosis is None:
            self.differential_diagnosis = []
        if self.recommendations is None:
            self.recommendations = []
        if not self.study_date:
            self.study_date = datetime.now().strftime("%Y-%m-%d")


class PDFReportGenerator:
    """Generates clinical PDF reports using ReportLab."""

    TITLE = "MedXplain-Simple — AI-Assisted Medical Image Analysis Report"
    DISCLAIMER = (
        "DISCLAIMER: This report is generated by an AI research prototype "
        "(MedXplain-Simple) and is NOT intended for clinical decision-making "
        "without proper validation by a qualified medical professional. "
        "All findings require clinical correlation."
    )

    def __init__(self):
        self._check_reportlab()

    @staticmethod
    def _check_reportlab():
        try:
            import reportlab  # noqa: F401
        except ImportError:
            raise ImportError(
                "reportlab is required for PDF generation. "
                "Install via: pip install reportlab"
            )

    def generate(self, data: ReportData) -> bytes:
        """Generate a PDF report and return it as bytes.

        Parameters
        ----------
        data : ReportData
            All the data to include in the report.

        Returns
        -------
        bytes
            The generated PDF as bytes.
        """
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import cm, mm
        from reportlab.platypus import (
            Image as RLImage,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
            leftMargin=2 * cm,
            rightMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontSize=16,
            spaceAfter=6 * mm,
            textColor=colors.HexColor("#1a365d"),
        )
        heading_style = ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontSize=13,
            spaceAfter=3 * mm,
            spaceBefore=6 * mm,
            textColor=colors.HexColor("#2c5282"),
        )
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["Normal"],
            fontSize=10,
            leading=14,
            spaceAfter=3 * mm,
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#e53e3e"),
            spaceBefore=10 * mm,
        )

        elements = []

        # Title
        elements.append(Paragraph(self.TITLE, title_style))
        elements.append(Spacer(1, 4 * mm))

        # Patient / study info table
        info_data = [
            ["Patient ID", data.patient_id, "Study Date", data.study_date],
            ["Modality", data.modality or "N/A", "Body Part", data.body_part or "N/A"],
            ["Model Used", data.model_used, "Processing Time", f"{data.processing_time_ms:.0f} ms"],
            ["Report Generated", datetime.now().strftime("%Y-%m-%d %H:%M UTC"), "Confidence", f"{data.confidence:.1%}"],
        ]
        info_table = Table(info_data, colWidths=[3.5 * cm, 5 * cm, 3.5 * cm, 5 * cm])
        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#edf2f7")),
            ("BACKGROUND", (2, 0), (2, -1), colors.HexColor("#edf2f7")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e0")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(info_table)

        # Clinical Question
        elements.append(Paragraph("Clinical Question", heading_style))
        elements.append(Paragraph(data.clinical_question or "N/A", body_style))

        # VQA Analysis
        elements.append(Paragraph("AI Analysis — VQA Response", heading_style))
        elements.append(Paragraph(data.vqa_answer or "N/A", body_style))

        # Clinical Reasoning
        if data.clinical_reasoning:
            elements.append(Paragraph("Clinical Reasoning", heading_style))
            elements.append(Paragraph(data.clinical_reasoning, body_style))

        # Differential Diagnosis
        if data.differential_diagnosis:
            elements.append(Paragraph("Differential Diagnosis", heading_style))
            for i, dx in enumerate(data.differential_diagnosis, 1):
                elements.append(Paragraph(f"{i}. {dx}", body_style))

        # Recommendations
        if data.recommendations:
            elements.append(Paragraph("Recommendations", heading_style))
            for i, rec in enumerate(data.recommendations, 1):
                elements.append(Paragraph(f"{i}. {rec}", body_style))

        # Grad-CAM Heatmap
        if data.heatmap_base64:
            elements.append(Paragraph("Explainability — Grad-CAM Heatmap", heading_style))
            elements.append(Paragraph(
                "The heatmap below highlights image regions that most influenced "
                "the AI model's prediction. Warmer colours (red/yellow) indicate "
                "higher activation.",
                body_style,
            ))
            try:
                img_data = base64.b64decode(data.heatmap_base64)
                img_buf = io.BytesIO(img_data)
                elements.append(Spacer(1, 2 * mm))
                elements.append(RLImage(img_buf, width=12 * cm, height=12 * cm))
            except Exception as e:
                elements.append(Paragraph(f"[Heatmap unavailable: {e}]", body_style))

        # Longitudinal Comparison
        if data.ssim_score is not None:
            elements.append(Paragraph("Longitudinal Comparison (SSIM)", heading_style))
            elements.append(Paragraph(
                f"SSIM Score: {data.ssim_score:.4f}",
                body_style,
            ))
            if data.comparison_summary:
                elements.append(Paragraph(data.comparison_summary, body_style))
            if data.comparison_base64:
                try:
                    img_data = base64.b64decode(data.comparison_base64)
                    img_buf = io.BytesIO(img_data)
                    elements.append(RLImage(img_buf, width=12 * cm, height=12 * cm))
                except Exception as e:
                    elements.append(Paragraph(f"[Comparison image unavailable: {e}]", body_style))

        # Disclaimer
        elements.append(Spacer(1, 6 * mm))
        elements.append(Paragraph(self.DISCLAIMER, disclaimer_style))

        doc.build(elements)
        return buffer.getvalue()

    def save(self, data: ReportData, output_path: str | Path) -> Path:
        """Generate and save a PDF report to disk."""
        pdf_bytes = self.generate(data)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(pdf_bytes)
        logger.info("Report saved to %s (%d bytes)", path, len(pdf_bytes))
        return path
